### PR TITLE
Create ExampleWithVirtualNetworkRules

### PR DESCRIPTION
**Pull request by AzimUddin**
[mysql-template - Copy.zip](https://github.com/Azure/azure-mysql/files/2317035/mysql-template.-.Copy.zip)

Enabling VNet Service endpoint during provisioning

### CODE REVIEW

**Comment by AzimUddin** [comment]
Added ARM template and parameters file with example on how to enable VNet Service endpoint using nested resource - can be a workaround for customers looking for an ARM template to enable VNet service endpoint during provisioning, until our provisioning directly supports it.

**Comment by bolzmj** [comment]
This is a handy ARM template. I recommend merge. A couple of things to note on this template is that 1) you must create the vnet and subnet before running this script and 2) it does not turn on service endpoints on the vnet if you do not already have it on.

**Comment by bolzmj** [comment]
Tested and passed 8/24/2018 by Mark Bolz

**Comment by ajlam** [comment]
Templates merged in #6

**Pull request closed without merging**
